---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1
names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Mat1 <- matrix(c(1:6),2,3)
Mat1
names(Mat1) 
```

```{r}
names(Mat1) <- letters[1:6]
names(Mat1)
```

```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
colnames(matObj1) 
rownames(matObj1)
```

```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```

```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(元素1=1,元素2="Hello",元素3=TRUE)
b
b[[3]] <- FALSE
b[[5]] <- 7
b
```

```{r}
b[["新元素A"]] <- c(1,3,2)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",col_types = cols(匯率 = col_number(),期間 = col_character()))
```

```{r}
library(lubridate)
ymd(exData3$期間) -> exData3$期間
class(exData3$期間)
```

```{r}
exData3$期間 >= ymd("1997-06-01") -> ac1
exData3$期間 <= ymd("1998-12-01") -> ac2
ac1 == TRUE & ac2 == TRUE -> isAsiaCrisis
isAsiaCrisis -> exData3$isAsiaCrisis
exData3$isAsiaCrisis
```

```{r}
exData3[isAsiaCrisis,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*transcriptDataFinal$學分數[logiChosenStudent])/sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
transcriptDataFinal$學號=="223S63286" -> tl
transcriptDataFinal$學號=="105S60ba1" -> ol
sum(transcriptDataFinal$學期成績[tl]*transcriptDataFinal$學分數[tl])/sum(transcriptDataFinal$學分數[tl]) -> GPA2
sum(transcriptDataFinal$學期成績[ol]*transcriptDataFinal$學分數[ol])/sum(transcriptDataFinal$學分數[ol]) -> GPA1
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
utility_cobb_douglass(1,2,.beta = 0.8,.alpha = 0.5)
```

```{r}
supply_fun <- function(a,b,P){sp <- a+b*P
return(sp)}
demand_fun <- function(c,d,P){dm <- c-d*P
return(dm)}
supply_fun(0,1,1)
demand_fun(5,1,1)
```

