---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---

```{r}
Vec1 <- c(1:6)
Vec1
```

```{r}
Mat1 <- matrix(c(1:6),2,3)
Mat1
class(Mat1)
typeof(Mat1)
Mat1[[2]]
```

```{r}
Mat2 <- matrix(c("a","b","c","d"),2,2)
Mat2
class(Mat2)
typeof(Mat2)
Mat2[[2]]
Mat2[c(T,F,F,T)]
Mat2[c(1,4)]
```

```{r}
StuList <- list(學號=c(172,214,322,425,517), 姓名=c("小明","大雄","胖虎","小新","大白"), 成績=c(80,60,90,70,50))
StuList
```

```{r}
StuDF <- data.frame(學號=c(172,214,322,425,517), 姓名=c("小明","大雄","胖虎","小新","大白"), 成績=c(80,60,90,70,50))
StuDF
```

```{r}
StuDF[[2]][[3]]
as.data.frame(StuDF)
```

```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
```

```{r}
chosenLETTERS[[8]]
matObj1[8]
```

```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

