---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---
```{r}
library(stringr)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]
```

```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```

```{r}
for(i in c(1:5)){
  print(i) 
}
```

```{r}
for(i in c(1:5)){
  print(studentIds5[[i]]) # 
}
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for(i in seq_along(gmailAddress)){
  print(gmailAddress[[i]])
}
```

```{r}
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}
cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]][["commit"]][["author"]][["name"]])
}
```

```{r}
for(i in seq_along(commitHistory)){
  print(
    str_c(
      "Author is ",
      commitHistory[[i]][["commit"]][["author"]][["name"]],
      ". Committer is ",
      commitHistory[[i]][["commit"]][["committer"]][["name"]]
      )
    )
}
```

```{r}
for(i in seq_along(commitHistory)){
  commitHistory[[i]][["commit"]][["author"]][["name"]] == commitHistory[[i]][["commit"]][["committer"]][["name"]] -> logiResult
  print(logiResult)
}
```

```{r}
saveCharacter <- vector("character",5)
saveCharacter
saveNumeric <- vector("numeric",5)
saveNumeric
saveLogical <- vector("logical",5)
saveLogical
saveList <- vector("list",5)
saveList
```

```{r}
# 把"你好"存在saveCharacter第3個位置
saveCharacter # 儲存前
saveCharacter[[3]] <- "你好"
saveCharacter # 儲存後
# 把 72.3 存在saveNumeric第3個位置
saveNumeric # 儲存前
saveNumeric[[3]] <- 72.3
saveNumeric # 儲存後
# 把 TRUE 存在saveLogical第3個位置
saveLogical # 儲存前
saveLogical[[3]] <- TRUE
saveLogical # 儲存後
# 把 list(姓名="小明",電話="02-86741111") 存在saveList第3個位置
saveList # 儲存前
saveList[[3]] <- list(姓名="小明",電話="02-86741111")
saveList # 儲存後
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # sequence_source
saveGPAs <- vector("numeric",length(studentIds)) # saveContainer
```

```{r}
i <- 1
saveGPAs[[i]] <- gpa_fun(studentIds[[i]])
saveGPAs
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # sequence_source
saveGPAs <- vector("numeric",length(studentIds)) # saveContainer
for(i in seq_along(studentIds)){
  saveGPAs[[i]] <- gpa_fun(studentIds[[i]])
}
```

```{r}
saveGPAsWithNames <- saveGPAs
names(saveGPAsWithNames) <- studentIds

saveGPAs[1:5] # 元素沒有名字
saveGPAsWithNames[1:5] # 元素有名字
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
saveCommitAuthor <-
  vector("character",length(commitHistory))
commitHistory
```

```{r}
i<- 1

commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
```

```{r}
saveCommitAuthor
```

```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}

saveCommitAuthor
```

```{r}
saveCommitCommitter <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$committer$name -> saveCommitCommitter[[i]]
}

saveCommitCommitter
```

```{r}
saveEveryThing <- vector("list",length(commitHistory))
saveSameLogi <- vector("logical",length(commitHistory))
```

```{r}
i <- 1

author_i <- commitHistory[[i]]$commit$author$name
committer_i <- commitHistory[[i]]$commit$committer$name
commitDate_i <- commitHistory[[i]]$commit$committer$date

(author_i==committer_i) -> saveSameLogi[[i]]
list(
  author=author_i,
  committer=committer_i,
  commitDate=commitDate_i
) -> saveEveryThing[[i]]
```

```{r}
saveEveryThing
saveSameLogi
```

```{r}
saveEveryThing <- vector("list",length(commitHistory))
saveSameLogi <- vector("logical",length(commitHistory))
for(i in seq_along(commitHistory)){
  author_i <- commitHistory[[i]]$commit$author$name
  committer_i <- commitHistory[[i]]$commit$committer$name
  commitDate_i <- commitHistory[[i]]$commit$committer$date

  (author_i == committer_i) -> saveSameLogi[[i]]

  list(
    author=author_i,
    committer=committer_i,
    commitDate=commitDate_i
  ) -> saveEveryThing[[i]]  
}
saveEveryThing
print(saveSameLogi)
saveEveryThing[saveSameLogi] -> saveValidCommitDate
saveValidCommitDate
```

