---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
class(a+bL)
class(aL+bL)
class(a-bL)
class(aL-bL)
class(a*bL)
class(aL*bL)
class(a/bL)
class(aL/bL)
```

```{r}
a+b
a-b
a*b
a/b
```

```{r}
a+4
a^b
a %% b
```

```{r}
library(lubridate)
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
ymd("2019-08-11")-ymd("2000-02-01")
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```

```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x2
y2
x2 > y2
x2 < y2
x2 <= y2
x2 >= y2
x2 == y2
x2 != y2
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3
y3
x3 == y3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x6 <- c(1,NA,10)
y6 <- c(-1,NA,20)
x7 <- c(NA,"小花")
y7 <- c(NA,"小華")
```

```{r}
is.na(x6)
is.na(y6)
is.na(x7)
is.na(y7)
```

```{r}
sum(x2)
sum(x6)
```

