---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"','小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'","小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,FALSE,FALSE,FALSE)
class(aLogical)
```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

```{r}
studentMajors <- factor(c("經濟系","經濟系","法律系"))
```

```{r}
typeof(studentMajors)
levels(studentMajors)
```

```{r}
studentMajors
```

```{r}
as.integer(studentMajors)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(c("1970-01-01 00:02:53","1980-02-11 11:25:22"))
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
as.integer(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```

```{r}
TokyoDateTime <- with_tz(twDateTime,tzone="Asia/Tokyo")
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
```

```{r}
mdy_hms("3/14/2019 8:18:47", tz="Asia/Taipei") -> google
```

```{r}
ymd("2018-09-11", tz="Asia/Taipei") -> a
mdy("March 3, 2019", tz="Asia/Taipei") -> b
```

